src/View/Web/Controllers/Main/IndexController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Resources;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Web.Controllers.Base;
using Web.LanguagesView;

namespace Web.Controllers.Main
{
    public class IndexController : BaseController
    {
        // GET: Index
        public ActionResult Index()
        {

           


            return View();
        }


        public ActionResult ChangeCulture(string ddlCulture)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(ddlCulture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(ddlCulture);
            HttpCookie cookieLange = new HttpCookie("CurrentCulture", ddlCulture);
            Response.AppendCookie(cookieLange); 
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }
        //[HttpGet]
        //[Route("{email}/{password}/")]
        //FormCollection 
        [HttpPost]
        public ActionResult Add(UserViewModel user)
        {

            if (ModelState.IsValid)
            {

            }
            return View();
        }
    }
}

src/View/Web/Controllers/User/RegisterController.cs
using Core.IService.User;
using System.ComponentModel.Composition;
using System.Web.Mvc;
using Web.Controllers.Base;

namespace Web.Controllers.User
{
    [Export]
    public class RegisterController :UserController
    {
        [Import]
        protected IUserDataAccess ApplicationService { set; get; }
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Add()
        {
            ApplicationService.DeleteCollect(111);
            return Json("");
        }
    }
}

src/View/Web/Views/Register/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

@{
    ViewBag.Title = Resources.WebResources.Title;
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div class="col-md-4">
        <form method="post" action="@Url.Action("ChangeCulture", "Index")" >
            <p>@Resources.WebResources.SelectLanuage :
            <select onchange="this.form.submit()" name="ddlCulture" id="ddlCulture">
                
                 <option value="zh-CN" @(Request.Cookies["CurrentCulture"].Value.Equals("zh-CN") ? "selected" : "")>@Resources.WebResources.Chinese</option>
                 <option value="en-Us" @(Request.Cookies["CurrentCulture"].Value.Equals("en-Us") ? "selected" : "")>@Resources.WebResources.English</option>
                 
                 </select>  
            </p>
        </form>
    </div>


    <br />
    <form method="post" action="@Url.Action("Add","Register")">

        <div class="form-horizontal">
            <div class="form-group">
                <label>@Resources.WebResources.UserName </label>
                <div class="col-md-10">
                    <input type="text" />
                </div>
            </div>

            <div class="form-group">
                <label>@Resources.WebResources.FullName</label>
                <div class="col-md-10">
                    <input type="text" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@Resources.WebResources.Save" class=" btn btn-default" />
                </div>
            </div>
        </div>
    </form>
</body>
</html>