src/View/Web/Controllers/Main/IndexController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Resources;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Web.Controllers.Base;
using Web.LanguagesView;

namespace Web.Controllers.Main
{
    public class IndexController : BaseController
    {
        // GET: Index
        public ActionResult Index()
        {

           


            return View();
        }


        public ActionResult ChangeCulture(string ddlCulture)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(ddlCulture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(ddlCulture);
            HttpCookie cookieLange = new HttpCookie("CurrentCulture", ddlCulture);
            Response.AppendCookie(cookieLange); 
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }
        //[HttpGet]
        //[Route("{email}/{password}/")]
        //FormCollection 
        [HttpPost]
        public ActionResult Add(UserViewModel user)
        {

            if (ModelState.IsValid)
            {

            }
            return View();
        }
    }
}

src/View/Web/Controllers/Main/KetcherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers.Main
{
    public class KetcherController : Controller
    {
        // GET: Ketcher
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/View/Web/Controllers/Main/MainController.cs
using Core.IData.Log;
using Core.Model.Log;
using System.ComponentModel.Composition;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Web.Controllers.Base;
using Web.LanguagesView;

namespace Web.Controllers.Main
{
    [Export]
    public class MainController : WebController
    {
        
        // GET: Index
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Test()
        {
            return View();
        }

        public ActionResult ChangeCulture(string ddlCulture)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(ddlCulture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(ddlCulture);
            HttpCookie cookieLange = new HttpCookie("CurrentCulture", ddlCulture);
            Response.AppendCookie(cookieLange); 
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }
        //[HttpGet]
        //[Route("{email}/{password}/")]
        //FormCollection 
        [HttpPost]
        public ActionResult Add(UserViewModel user)
        {

            if (ModelState.IsValid)
            {

            }
            return View();
        }
    }
}

src/View/Web/Controllers/Main/MoleculeTransformController.cs
using Core.IService.User;
using System.ComponentModel.Composition;
using System.IO;
using System.Web.Mvc;
using Web.Controllers.Base;

namespace Web.Controllers.Main
{
    [Export]
    public class MoleculeTransformController : WebController
    {      

        

        public ActionResult GetMol()
        {
            return View();
        }

        public ActionResult GetSmile()
        {
            return View();
        }
        //[Route("{condition}/")]
        public ActionResult GetMolBySmilesOrName(string id)
        {
            WCF.ReactionWay.SearchServiceClient wcf = new WCF.ReactionWay.SearchServiceClient();
            string mol= wcf.GetMolByCasOrName(id, "");
            Message.body = mol;
            if (string.IsNullOrEmpty(mol))
            {
                Message.result.errCode = 1;
                Message.result.msg = Resources.WebResources.ResultMsgError;
            }
            else
            {
                Message.result.errCode = 0;
                Message.result.msg = Resources.WebResources.ResultMsgSuccess;
            }
            return JsonBase(Message);
        }
        public Stream GetPicture()
        {
            return new MemoryStream();
        }
    }
}

src/View/Web/Controllers/Main/SyntheticController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Controllers.Base;

namespace Web.Controllers.Main
{
    [Export]
    public class SyntheticController : WebController
    {
        // GET: Synthetic
        public ActionResult Index()
        {
            

            return View("2121212");
        }
    }
}

src/View/Web/Views/Main/Index.cshtml
@using Web.Views.Main.App_LocalResources
@{
    //ViewBag.Title= Index_cshtml.IndexPageTitle;
    Layout = "~/Views/Shared/SiteLayout.cshtml";
}

<div class="dimmer J_index_dimmer" style='display: block;position: absolute;opacity: .80;background: rgba(0,0,0,0.8);z-index: 1000;'>
    <div class="container ">
        <a class="arrow J_arrow" href="#">
            <i class="up_arrow"></i>
        </a>
    </div>
</div>
<div class="index_seach J_index_seach">
    <hgroup class='text'>
        <h1>@Index_cshtml.IndexTitle_1</h1>
        <h2>@Index_cshtml.IndexTitle_2</h2>
    </hgroup>
    <div class="J_index_form">
        <input class="searchTxt prompt" id="quick_search_param" name="q" placeholder="@Index_cshtml.InputRemind" type="text" autocomplete="off">
        <button type="button" name="commit" class="search_match" id="btnMatch" >@Index_cshtml.Match</button>
        <button class="search_draw J_search_draw">@Index_cshtml.Draw</button>
    </div>
</div>
<div class="desktop_page J_desktop_page">
    <div class="container ">
        <div class="sfBox" style='border: 1px solid #fff;height:auto;min-height:400px'>
            <iframe onload="loadMol()" id="ketcherFrame" name="ketcherFrame" style="min-width:610px;min-height:510px;width:100%;height:100%;border-style:none" src="Ketcher/index?ketcher_maximize" scrolling="no"></iframe>
        </div>
        <div class="sfCont">
            <input class="sfSearchBtn" type="button" value="Search">
        </div>
    </div>
</div>
<div class="goback J_goback">
    <i class="up_arrow"></i>
</div>
<script type="text/javascript" src="~/Scripts/Ketcher/prototype-min.js"></script>
<script type="text/javascript">
    function getKetcher() {
        var frame = null;

        if ('frames' in window && 'ketcherFrame' in window.frames)
            frame = window.frames['ketcherFrame'];
        else
            return null;

        if ('window' in frame)
            return frame.window.ketcher;
    }

    function getSmiles() {
        var ketcher = getKetcher();

        if (ketcher)
            $('textarea').value = ketcher.getSmiles();
    }

    function getMolfile() {
        var ketcher = getKetcher();

        if (ketcher)
            $('textarea').value = ketcher.getMolfile();
    }

    var row = 1;

    function render() {
        var molfile = $('textarea').value;

        var smiles = molfile.strip();

        if (smiles == '' || smiles.indexOf('\n') == -1) {
            alert("Please, input Molfile");
            return;
        }

        var renderOpts = {
            'autoScale': true,
            'debug': true,
            'autoScaleMargin': 20,
            'ignoreMouseEvents': true
        };

        var newRow = new Element('tr');

        newRow.update('<td id="row' + row + '" style="width:100%;height:100px;padding:0px;"></td>');
        $('table').insert(newRow);

        var ketcher = getKetcher();

        rowObject = $('row' + row);
        //alert(rowObject['clientWidth']);
        //rowObject.innerHTML = "asdasdf";
        if (ketcher.showMolfileOpts(rowObject, molfile, 20, renderOpts))
            row++;
    }

    function loadStructure() {
        var ketcher = getKetcher();
        ketcher.setMolecule($('textarea').value);
    }

    function loadFragment() {
        var ketcher = getKetcher();
        ketcher.addFragment($('textarea').value);
    }

    function loadMol(mol) {
        initialMolecule =
            [
                mol
            ].join("\n");
        var ketcher = getKetcher();
        ketcher.setMolecule(initialMolecule);
    }

</script>
@section script{
<script type="text/javascript">
    $("#btnMatch").click(function () {
        var condition = $("#quick_search_param").val();
        if (condition=="") {
            layer.msg("@Index_cshtml.MatchNullMsg");
            return;
        }
        $.get("@Url.Action("GetMolBySmilesOrName", "MoleculeTransform")" + "/" + condition, function (data) {
            console.log(data);
            if (data.result.errCode == 0) {
                loadMol(data.body);
                $(".J_search_draw").click();
            }
            else {

            }
        },"json")
    });

    $(".sfSearchBtn").click(function () {
        var ketcher = getKetcher();
        var smiles = ketcher.getSmiles();
        if (smiles == "") {
            alert("2121212121");
            return;
        }
        var form = $("<form name='formSmiles'/>").attr("action", "@Url.Action("Index", "SyntheticController")");
        var input = $("<input type='hidden'/>").attr("name", "hidSmiles").val(smiles);
        form.append(input);
        form.submit();
    });

</script>
}